apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  labels:
    app: petclinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      containers:
      - name: petclinic-container
        image: shivapetclinicacr.azurecr.io/spring-petclinic:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: LoadBalancer
  selector:
    app: petclinic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080